apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ClassClaim
metadata:
  annotations:
    classclaims.services.apps.tanzu.vmware.com/xrd-name: xpostgresqlinstances.bitnami.database.tanzu.vmware.com
  name: customer-database
  namespace: mae
spec:
  classRef:
    name: postgresql-unmanaged
  parameters:
    parameters:
      storageGB: 32